# Generated by Django 5.0.1 on 2024-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploadingdate',
            field=models.DateTimeField(max_length=30),
        ),
    ]
