# Generated by Django 5.0.1 on 2024-01-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_description_alter_notes_uploadingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('All', 'All')], default='Pending', max_length=15, null=True),
        ),
    ]
