# Generated by Django 5.0.1 on 2024-01-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_notesfile_alter_notes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('All', 'All')], max_length=15, null=True),
        ),
    ]
